@Authorization=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJ3bHNkaEBnbWFpbC5jb20iLCJuaWNrbmFtZSI6Ik9yZGVyIiwidXNlclJvbGUiOiJBRE1JTiIsImV4cCI6MTczMjA4ODg5MiwiaWF0IjoxNzMyMDg1MjkyfQ.BG2GBgHdR_Rl5se6UxcEZxgcG7ZCx1hhGQDUKf8-ILc

### 회원가입
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "wlsdh@gmail.com",
  "password": "wlsdh741@",
  "userRole": "USER"
}

### 로그인
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "email": "wlsdh@gmail.com",
  "password": "wlsdh741@"
}

### 할일 저장
POST http://localhost:8080/todos?page={{$random.integer(100)}}&size={{$random.integer(100)}}
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "title": "test",
  "contents": "test"
}

### 토큰에 있는 닉네임 불러오기
GET http://localhost:8080/users/profile
Authorization: Bearer {{Authorization}}
Content-Type: application/json

### 권한 변경
PATCH http://localhost:8080/admin/users/1
Authorization: Bearer {{Authorization}}
Content-Type: application/json

{
  "role": "USER"
}